export const userTypes = {
    TUTOR:   { userTypeId: 1, userTypeDesc: 'Tutor',   pathname: '/user-registration-tutor'   },
    STUDENT: { userTypeId: 2, userTypeDesc: 'Student', pathname: '/user-registration-student' },
    PARENT:  { userTypeId: 3, userTypeDesc: 'Parent',  pathname: '/user-registration-parent'  },
    CHILD:   { userTypeId: 4, userTypeDesc: 'Child',   pathname: '/user-registration-child'   },
};

export const userTitles = [
    { key: "0", value: "Select", gender: ''},
    { key: "1", value: "Mrs",    gender: 'F'},
    { key: "2", value: "Miss",   gender: 'F'},
    { key: "3", value: "Ms",     gender: 'F'},
    { key: "4", value: "Mr",     gender: 'M'},
];

export const countries = [
    { key: "0", value: "Select"},
    { key: "1", value: "Afghanistan"},
    { key: "2", value: "Aland Islands"},
    { key: "3", value: "Albania"},
    { key: "4", value: "Algeria"},
    { key: "5", value: "American Samoa"},
    { key: "6", value: "Andorra"},
    { key: "7", value: "Angola"},
    { key: "8", value: "Anguilla"},
    { key: "9", value: "Antarctica"},
    { key: "10", value: "Antigua and Barbuda"},
    { key: "11", value: "Argentina"},
    { key: "12", value: "Armenia"},
    { key: "13", value: "Aruba"},
    { key: "14", value: "Australia"},
    { key: "15", value: "Austria"},
    { key: "16", value: "Azerbaijan"},
    { key: "17", value: "Bahamas"},
    { key: "18", value: "Bahrain"},
    { key: "19", value: "Bangladesh"},
    { key: "20", value: "Barbados"},
    { key: "21", value: "Belarus"},
    { key: "22", value: "Belgium"},
    { key: "23", value: "Belize"},
    { key: "24", value: "Benin"},
    { key: "25", value: "Bermuda"},
    { key: "26", value: "Bhutan"},
    { key: "27", value: "Bolivia"},
    { key: "28", value: "Bonaire, Saint Eustatius and Saba "},
    { key: "29", value: "Bosnia and Herzegovina"},
    { key: "30", value: "Botswana"},
    { key: "31", value: "Bouvet Island"},
    { key: "32", value: "Brazil"},
    { key: "33", value: "British Indian Ocean Territory"},
    { key: "34", value: "British Virgin Islands"},
    { key: "35", value: "Brunei"},
    { key: "36", value: "Bulgaria"},
    { key: "37", value: "Burkina Faso"},
    { key: "38", value: "Burundi"},
    { key: "39", value: "Cabo Verde"},
    { key: "40", value: "Cambodia"},
    { key: "41", value: "Cameroon"},
    { key: "42", value: "Canada"},
    { key: "43", value: "Cayman Islands"},
    { key: "44", value: "Central African Republic"},
    { key: "45", value: "Chad"},
    { key: "46", value: "Chile"},
    { key: "47", value: "China"},
    { key: "48", value: "Christmas Island"},
    { key: "49", value: "Cocos Islands"},
    { key: "50", value: "Colombia"},
    { key: "51", value: "Comoros"},
    { key: "52", value: "Cook Islands"},
    { key: "53", value: "Costa Rica"},
    { key: "54", value: "Croatia"},
    { key: "55", value: "Cuba"},
    { key: "56", value: "Curacao"},
    { key: "57", value: "Cyprus"},
    { key: "58", value: "Czechia"},
    { key: "59", value: "Democratic Republic of the Congo"},
    { key: "60", value: "Denmark"},
    { key: "61", value: "Djibouti"},
    { key: "62", value: "Dominica"},
    { key: "63", value: "Dominican Republic"},
    { key: "64", value: "Ecuador"},
    { key: "65", value: "Egypt"},
    { key: "66", value: "El Salvador"},
    { key: "67", value: "Equatorial Guinea"},
    { key: "68", value: "Eritrea"},
    { key: "69", value: "Estonia"},
    { key: "70", value: "Eswatini"},
    { key: "71", value: "Ethiopia"},
    { key: "72", value: "Falkland Islands"},
    { key: "73", value: "Faroe Islands"},
    { key: "74", value: "Fiji"},
    { key: "75", value: "Finland"},
    { key: "76", value: "France"},
    { key: "77", value: "French Guiana"},
    { key: "78", value: "French Polynesia"},
    { key: "79", value: "French Southern Territories"},
    { key: "80", value: "Gabon"},
    { key: "81", value: "Gambia"},
    { key: "82", value: "Georgia"},
    { key: "83", value: "Germany"},
    { key: "84", value: "Ghana"},
    { key: "85", value: "Gibraltar"},
    { key: "86", value: "Greece"},
    { key: "87", value: "Greenland"},
    { key: "88", value: "Grenada"},
    { key: "89", value: "Guadeloupe"},
    { key: "90", value: "Guam"},
    { key: "91", value: "Guatemala"},
    { key: "92", value: "Guernsey"},
    { key: "93", value: "Guinea"},
    { key: "94", value: "Guinea-Bissau"},
    { key: "95", value: "Guyana"},
    { key: "96", value: "Haiti"},
    { key: "97", value: "Heard Island and McDonald Islands"},
    { key: "98", value: "Honduras"},
    { key: "99", value: "Hong Kong"},
    { key: "100", value: "Hungary"},
    { key: "101", value: "Iceland"},
    { key: "102", value: "India"},
    { key: "103", value: "Indonesia"},
    { key: "104", value: "Iran"},
    { key: "105", value: "Iraq"},
    { key: "106", value: "Ireland"},
    { key: "107", value: "Isle of Man"},
    { key: "108", value: "Israel"},
    { key: "109", value: "Italy"},
    { key: "110", value: "Ivory Coast"},
    { key: "111", value: "Jamaica"},
    { key: "112", value: "Japan"},
    { key: "113", value: "Jersey"},
    { key: "114", value: "Jordan"},
    { key: "115", value: "Kazakhstan"},
    { key: "116", value: "Kenya"},
    { key: "117", value: "Kiribati"},
    { key: "118", value: "Kosovo"},
    { key: "119", value: "Kuwait"},
    { key: "120", value: "Kyrgyzstan"},
    { key: "121", value: "Laos"},
    { key: "122", value: "Latvia"},
    { key: "123", value: "Lebanon"},
    { key: "124", value: "Lesotho"},
    { key: "125", value: "Liberia"},
    { key: "126", value: "Libya"},
    { key: "127", value: "Liechtenstein"},
    { key: "128", value: "Lithuania"},
    { key: "129", value: "Luxembourg"},
    { key: "130", value: "Macao"},
    { key: "131", value: "Madagascar"},
    { key: "132", value: "Malawi"},
    { key: "133", value: "Malaysia"},
    { key: "134", value: "Maldives"},
    { key: "135", value: "Mali"},
    { key: "136", value: "Malta"},
    { key: "137", value: "Marshall Islands"},
    { key: "138", value: "Martinique"},
    { key: "139", value: "Mauritania"},
    { key: "140", value: "Mauritius"},
    { key: "141", value: "Mayotte"},
    { key: "142", value: "Mexico"},
    { key: "143", value: "Micronesia"},
    { key: "144", value: "Moldova"},
    { key: "145", value: "Monaco"},
    { key: "146", value: "Mongolia"},
    { key: "147", value: "Montenegro"},
    { key: "148", value: "Montserrat"},
    { key: "149", value: "Morocco"},
    { key: "150", value: "Mozambique"},
    { key: "151", value: "Myanmar"},
    { key: "152", value: "Namibia"},
    { key: "153", value: "Nauru"},
    { key: "154", value: "Nepal"},
    { key: "155", value: "Netherlands"},
    { key: "156", value: "Netherlands Antilles"},
    { key: "157", value: "New Caledonia"},
    { key: "158", value: "New Zealand"},
    { key: "159", value: "Nicaragua"},
    { key: "160", value: "Niger"},
    { key: "161", value: "Nigeria"},
    { key: "162", value: "Niue"},
    { key: "163", value: "Norfolk Island"},
    { key: "164", value: "North Korea"},
    { key: "165", value: "North Macedonia"},
    { key: "166", value: "Northern Mariana Islands"},
    { key: "167", value: "Norway"},
    { key: "168", value: "Oman"},
    { key: "169", value: "Pakistan"},
    { key: "170", value: "Palau"},
    { key: "171", value: "Palestinian Territory"},
    { key: "172", value: "Panama"},
    { key: "173", value: "Papua New Guinea"},
    { key: "174", value: "Paraguay"},
    { key: "175", value: "Peru"},
    { key: "176", value: "Philippines"},
    { key: "177", value: "Pitcairn"},
    { key: "178", value: "Poland"},
    { key: "179", value: "Portugal"},
    { key: "180", value: "Puerto Rico"},
    { key: "181", value: "Qatar"},
    { key: "182", value: "Republic of the Congo"},
    { key: "183", value: "Reunion"},
    { key: "184", value: "Romania"},
    { key: "185", value: "Russia"},
    { key: "186", value: "Rwanda"},
    { key: "187", value: "Saint Barthelemy"},
    { key: "188", value: "Saint Helena"},
    { key: "189", value: "Saint Kitts and Nevis"},
    { key: "190", value: "Saint Lucia"},
    { key: "191", value: "Saint Martin"},
    { key: "192", value: "Saint Pierre and Miquelon"},
    { key: "193", value: "Saint Vincent and the Grenadines"},
    { key: "194", value: "Samoa"},
    { key: "195", value: "San Marino"},
    { key: "196", value: "Sao Tome and Principe"},
    { key: "197", value: "Saudi Arabia"},
    { key: "198", value: "Senegal"},
    { key: "199", value: "Serbia"},
    { key: "200", value: "Serbia and Montenegro"},
    { key: "201", value: "Seychelles"},
    { key: "202", value: "Sierra Leone"},
    { key: "203", value: "Singapore"},
    { key: "204", value: "Sint Maarten"},
    { key: "205", value: "Slovakia"},
    { key: "206", value: "Slovenia"},
    { key: "207", value: "Solomon Islands"},
    { key: "208", value: "Somalia"},
    { key: "209", value: "South Africa"},
    { key: "210", value: "South Georgia and the South Sandwich Islands"},
    { key: "211", value: "South Korea"},
    { key: "212", value: "South Sudan"},
    { key: "213", value: "Spain"},
    { key: "214", value: "Sri Lanka"},
    { key: "215", value: "Sudan"},
    { key: "216", value: "Suriname"},
    { key: "217", value: "Svalbard and Jan Mayen"},
    { key: "218", value: "Sweden"},
    { key: "219", value: "Switzerland"},
    { key: "220", value: "Syria"},
    { key: "221", value: "Taiwan"},
    { key: "222", value: "Tajikistan"},
    { key: "223", value: "Tanzania"},
    { key: "224", value: "Thailand"},
    { key: "225", value: "Timor Leste"},
    { key: "226", value: "Togo"},
    { key: "227", value: "Tokelau"},
    { key: "228", value: "Tonga"},
    { key: "229", value: "Trinidad and Tobago"},
    { key: "230", value: "Tunisia"},
    { key: "231", value: "Turkey"},
    { key: "232", value: "Turkmenistan"},
    { key: "233", value: "Turks and Caicos Islands"},
    { key: "234", value: "Tuvalu"},
    { key: "235", value: "U.S. Virgin Islands"},
    { key: "236", value: "Uganda"},
    { key: "237", value: "Ukraine"},
    { key: "238", value: "United Arab Emirates"},
    { key: "239", value: "United Kingdom"},
    { key: "240", value: "United States"},
    { key: "241", value: "United States Minor Outlying Islands"},
    { key: "242", value: "Uruguay"},
    { key: "243", value: "Uzbekistan"},
    { key: "244", value: "Vanuatu"},
    { key: "245", value: "Vatican"},
    { key: "246", value: "Venezuela"},
    { key: "247", value: "Vietnam"},
    { key: "248", value: "Wallis and Futuna"},
    { key: "249", value: "Western Sahara"},
    { key: "250", value: "Yemen"},
    { key: "251", value: "Zambia"},
    { key: "252", value: "Zimbabwe"},
];
